#
# Module manifest for module 'posh-with'
#
# Generated by: Jan
#
# Generated on: 24-Aug-16
#

@{

# Version number of this module.
ModuleVersion = '1.0.1'

# Script module or binary module file associated with this manifest.
RootModule = 'posh-with.psm1'

# ID used to uniquely identify this module
GUID = '52d68197-b642-4c8a-be08-16b92399f1f1'

# Company or vendor of this module
CompanyName = 'Unknown'

# Author of this module
Author = 'JanJoris'

# Copyright statement for this module
Copyright = '(c) 2016 JanJoris. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A PowerShell port of the Bash with commandlet'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# List of all files packaged with this module
FileList = @()

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = '*'

# Functions to export from this module
FunctionsToExport = @('Invoke-With', 'Write-WithPrompt')

# Private data to pass to the module specified in RootModule. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('git', 'with', 'repeat', 'bash', 'prompt')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/JanJoris/posh-with/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/JanJoris/posh-with'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}

